server_ip: 127.0.0.1
db_instance:  "(local)\\SQL2008R2,1433"
uid: sa
password: Jcbsc8860
update_url: "http://bltmld.vicp.cc:8090/hx"
update_file: "update.xml"

gis_instance: sde:sqlserver:127.0.0.1
gis_dbclient: sqlserver
gis_db_connection_properties: 127.0.0.1
gis_user: sde
gis_password: Jcbsc8860
gis_version: SDE.DEFAULT

coal_seams:
    - name:   "9#"
      db_name:   "C:\\DW9.sqlite3"
      gis_name:  "C:\\DW9.gdb"
      mxd_name:  "C:\\default_DW9.mxd"
      port: 8888
      rest_port: 7071

    - name:    "15#"
      db_name:   "C:\\DW15.sqlite3"
      gis_name:  "C:\\DW15.gdb"
      mxd_name:  "C:\\default_DW15.mxd"
      port: 8889
      rest_port: 7072